-- Run this once in Supabase SQL Editor.
alter table if exists public.student_requests
  add column if not exists reference_code text,
  add column if not exists transfer_info text not null default '',
  add column if not exists receipt text not null default '',
  add column if not exists payment_method text not null default '',
  add column if not exists payment_amount numeric not null default 0,
  add column if not exists payment_status text not null default 'pending' check (payment_status in ('pending', 'paid')),
  add column if not exists payment_date date;

create index if not exists student_requests_reference_idx on public.student_requests(reference_code);

create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  student_profile_id uuid not null references public.profiles(id) on delete cascade,
  instructor_profile_id uuid not null references public.profiles(id) on delete restrict,
  level text not null,
  status text not null check (status in ('present', 'absent', 'late')),
  session_date date not null,
  session_time time not null,
  notes text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists attendance_records_student_idx on public.attendance_records(student_profile_id, session_date desc);
create index if not exists attendance_records_instructor_idx on public.attendance_records(instructor_profile_id, session_date desc);

create table if not exists public.course_library (
  id bigint generated by default as identity primary key,
  level text not null,
  category text not null check (category in ('course', 'exercises', 'listening', 'listening_books', 'exam', 'dictionary', 'support')),
  title text not null,
  url text not null,
  visible boolean not null default true,
  instructor_profile_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.course_library add column if not exists visible boolean not null default true;
alter table public.course_library drop constraint if exists course_library_category_check;
alter table public.course_library add constraint course_library_category_check check (category in ('course', 'exercises', 'listening', 'listening_books', 'exam', 'dictionary', 'support'));

create index if not exists course_library_level_idx on public.course_library(level, category);

alter table public.course_library enable row level security;

drop policy if exists "Authenticated users can view course library" on public.course_library;
create policy "Authenticated users can view course library" on public.course_library
  for select to authenticated using (visible = true or exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role in ('admin', 'instructor')));

drop policy if exists "Instructors can add course library links" on public.course_library;
create policy "Instructors can add course library links" on public.course_library
  for insert to authenticated
  with check (instructor_profile_id = auth.uid() and exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'instructor'));

drop policy if exists "Instructors can delete course library links" on public.course_library;
create policy "Instructors can delete course library links" on public.course_library
  for delete to authenticated
  using (instructor_profile_id = auth.uid() and exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'instructor'));

drop policy if exists "Instructors can update course library links" on public.course_library;
create policy "Instructors can update course library links" on public.course_library
  for update to authenticated
  using (instructor_profile_id = auth.uid() and exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.role = 'instructor'))
  with check (instructor_profile_id = auth.uid());

alter table public.attendance_records enable row level security;

drop policy if exists "Students can view own attendance" on public.attendance_records;
create policy "Students can view own attendance" on public.attendance_records
  for select to authenticated
  using (student_profile_id = auth.uid());

drop policy if exists "Instructors can view assigned attendance" on public.attendance_records;
create policy "Instructors can view assigned attendance" on public.attendance_records
  for select to authenticated
  using (
    instructor_profile_id = auth.uid()
    and exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'instructor'
    )
  );

drop policy if exists "Instructors can record attendance" on public.attendance_records;
create policy "Instructors can record attendance" on public.attendance_records
  for insert to authenticated
  with check (
    instructor_profile_id = auth.uid()
    and exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'instructor'
    )
  );

-- Add this policy to allow request deletion by staff only.
drop policy if exists "Staff can delete student requests" on public.student_requests;
create policy "Staff can delete student requests" on public.student_requests
  for delete to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role in ('admin', 'instructor')
    )
  );
